### ISSUE TITLE
[Major Bug] Prevents me from accessing my settings

### ISSUE THREAD

**Issue by SheepCommander** [GDKID69/cps-counter#1]
https://user-images.githubusercontent.com/66646514/148472257-00e2b3fd-9a6a-41e4-b782-fe8a73dbb907.mp4

**Comment by SheepCommander** [comment]
Wait nvm it's not related this only started happening after I installed this so I assumed it was the cause

**Comment by fuh-Q** [comment]
> Wait nvm it's not related this only started happening after I installed this so I assumed it was the cause

Oh alright, glad it worked out!
